services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=philoagents
      - MONGODB_INITDB_ROOT_PASSWORD=philoagents
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - philoagents-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: futbolagents-jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - philoagents-network

  api:
    container_name: futbolagents-api
    build:
      context: ./futbolagents-api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
      - OTEL_ENABLED=true
      - JAEGER_ENDPOINT=http://jaeger:4317
    ports:
      - "8000:8000"
    env_file:
      - ./futbolagents-api/.env
    depends_on:
      - jaeger
    networks:
      - philoagents-network

  ui:
    container_name: futbolagents-ui
    build:
      context: ./futbolagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./futbolagents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - philoagents-network

volumes:
  data:
  config:

networks:
  philoagents-network:
    name: philoagents-network
